spring:
  application:
    name: common-platform-webhooks-mgmt-test
  
  # WebFlux Configuration
  webflux:
    base-path: /

  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  # Redis Configuration (for Spring Data Redis)
  data:
    redis:
      # These will be overridden by test containers via @DynamicPropertySource
      host: localhost
      port: 6379
      database: 0
      timeout: 10s
      connect-timeout: 10s
      ssl:
        enabled: false



# Server Configuration
server:
  port: 0  # Random port for tests

# Firefly Webhook Configuration
firefly:
  webhooks:
    destination:
      prefix: ""
      suffix: ""
      use-provider-as-topic: true
      custom: ""

  # Cache Configuration for Idempotency
  cache:
    enabled: true
    default-cache-type: REDIS
    caffeine:
      enabled: true
      cache-name: "webhook-idempotency-fallback"
      default-ttl: 7d
      max-size: 10000
    redis:
      cache-name: "webhook-idempotency"
      enabled: true
      # These will be overridden by test containers via @DynamicPropertySource
      host: localhost
      port: 6379
      database: 0
      key-prefix: "firefly:webhooks:test"
      default-ttl: 7d
      connection-timeout: 10s
      command-timeout: 5s
      ssl: false

  # EDA Configuration - Kafka bootstrap servers overridden by Testcontainers
  eda:
    enabled: true
    default-publisher-type: KAFKA
    metrics-enabled: true
    health-enabled: true

    # Publisher configuration - webhook platform publishes events to Kafka
    publishers:
      kafka:
        default:
          enabled: true
          # Bootstrap servers will be overridden by test containers
          bootstrap-servers: localhost:9092
          default-topic: events
          properties:
            acks: all
            retries: 1
            compression.type: snappy

    # Consumer configuration - test worker consumes webhook events
    # In production, separate worker applications would consume these events
    # Topics are now automatically discovered from @EventListener annotations
    # No need to configure topics manually - they are determined dynamically
    consumer:
      enabled: true
      group-id: webhook-worker-test
      kafka:
        default:
          enabled: true
          # Bootstrap servers will be overridden by test containers
          bootstrap-servers: localhost:9092
          auto-offset-reset: earliest  # Start from beginning for tests
          properties:
            enable.auto.commit: true
            auto.commit.interval.ms: 1000
            metadata.max.age.ms: 1000  # Refresh metadata frequently for tests

# Logging Configuration
logging:
  level:
    root: INFO
    com.firefly.common.webhooks: DEBUG
    com.firefly.common.eda: DEBUG
    com.firefly.common.cache: DEBUG
    org.apache.kafka: WARN
    org.testcontainers: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
